version: "3"

services:
  app:
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes:
      - .:/opt/app
    network_mode: host
    environment:
      - PORT=8080
    command: "./watch.sh"
