version: "3"

volumes:
  underscore_build:
  deps:
services:
  app:
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes:
      - .:/opt/app
      # - underscore_build:/opt/app/_build
      # - deps:/opt/app/deps
    network_mode: host
    environment:
      - PORT=8080
      - FRONTEND_URL=http://localhost:5000
